{
  assertTrue(true);
  assertTrue("We should be okay",true);
  try {
    assertTrue(false);
  }
 catch (  Throwable ex) {
    if (!(ex instanceof AssertionFailedError)) {
      fail("Unexpected type of exception during assertFalse(boolean) testing");
    }
  }
  try {
    assertTrue("This should be okay",false);
  }
 catch (  Throwable ex) {
    if (ex instanceof AssertionFailedError) {
      return;
    }
  }
  fail("Unexpected exception during assertTrue(String, boolean) testing");
}
