{
  assertEquals("",5,5);
  boolean exWasThrown=false;
  try {
    assertEquals("hello",5,4);
  }
 catch (  Throwable ex) {
    exWasThrown=true;
    if (!(ex instanceof AssertionFailedError)) {
      fail("Unexpected type of exception during assertEquals(String,int,int) testing");
    }
  }
  if (!exWasThrown) {
    fail("No exception was thrown during assertEquals(String,int,int) testing");
  }
}
