{
  final UmbrellaException expected=TestSetFactory.createUmbrellaException();
  checkException(expected,new AsyncCallback<UmbrellaException>(){
    @Override public void onFailure(    Throwable caught){
      TestSetValidator.rethrowException(caught);
    }
    @Override public void onSuccess(    UmbrellaException result){
      assertNotNull(result);
      assertTrue(TestSetValidator.isValid(expected,result));
      finishTest();
    }
  }
);
}
