{
  final UmbrellaException expected=TestSetFactory.createUmbrellaException();
  checkException(expected,new AsyncCallback<UmbrellaException>(){
    public void onFailure(    Throwable caught){
      TestSetValidator.rethrowException(caught);
    }
    public void onSuccess(    UmbrellaException result){
      assertNotNull(result);
      assertTrue(TestSetValidator.isValid(expected,result));
      finishTest();
    }
  }
);
}
