{
  int value=10;
  try {
    assertEquals(0,addCorrectOrder(throwMyException(),++value));
    fail();
  }
 catch (  MyException e) {
    assertEquals(10,value);
  }
  try {
    assertEquals(0,addReverseOrder(throwMyException(),++value));
    fail();
  }
 catch (  MyException e) {
    assertEquals(10,value);
  }
}
