{
  delayTestFinish(5000);
  SimpleFooProxy newFoo=req.create(SimpleFooProxy.class);
  final RequestObject<SimpleFooProxy> persistRequest=req.simpleFooRequest().persistAndReturnSelf(newFoo);
  final SimpleFooProxy mutableFoo=persistRequest.edit(newFoo);
  mutableFoo.setPleaseCrash(42);
  persistRequest.fire(new Receiver<SimpleFooProxy>(){
    @Override public void onFailure(    ServerFailure error){
      assertEquals("Server Error: THIS EXCEPTION IS EXPECTED BY A TEST",error.getMessage());
      assertEquals("",error.getExceptionType());
      assertEquals("",error.getStackTraceString());
      mutableFoo.setPleaseCrash(24);
      persistRequest.fire(new Receiver<SimpleFooProxy>(){
        @Override public void onSuccess(        SimpleFooProxy response){
          finishTestAndReset();
        }
      }
);
    }
    public void onSuccess(    SimpleFooProxy response){
      fail("Failure expected but onSuccess() was called");
    }
    @Override public void onViolation(    Set<Violation> errors){
      fail("Failure expected but onViolation() was called");
    }
  }
);
}
