{
  try {
    delegate.testResolverExceptionsGetWrappedInValidationException();
  }
 catch (  ValidationException expected) {
    Throwable cause=expected.getCause();
    assertEquals(RuntimeException.class,cause.getClass());
    assertTrue("isReachable failed".equals(cause.getMessage()) || "isCascadable failed".equals(cause.getMessage()));
  }
}
