{
  assertNotNull("Hello");
  assertNotNull("We should be okay","Hello");
  try {
    assertNotNull("Hello");
  }
 catch (  Throwable ex) {
    if (!(ex instanceof AssertionFailedError)) {
      fail("Unexpected type of exception during assertNotNull(Object) testing");
    }
  }
  try {
    assertNotNull("This should be okay",null);
  }
 catch (  Throwable ex) {
    if (ex instanceof AssertionFailedError) {
      return;
    }
  }
  fail("Unexpected exception during assertNotNull(String, Object) testing");
}
