{
  int value=10;
  try {
    assertEquals(0,addCorrectOrder(++value,throwMyException()));
    fail();
  }
 catch (  MyException e) {
    assertEquals(11,value);
  }
  try {
    assertEquals(0,addReverseOrder(++value,throwMyException()));
    fail();
  }
 catch (  MyException e) {
    assertEquals(12,value);
  }
}
